<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PersonnageManager {

	/**
	 * 
	 * @var PDO
	 * @access protected
	 */
	protected  $db;


	/**
	 * @access public
	 * @param PDO $db 
	 * @return void
	 */

	public final  function __construct(PDO $db) {

	}


	/**
	 * @access public
	 * @param Personnage $perso 
	 * @return void
	 */

	public final  function add(Personnage $perso) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function count() {

	}


	/**
	 * @access public
	 * @param Personnage $perso 
	 * @return void
	 */

	public final  function delete(Personnage $perso) {

	}


	/**
	 * @access public
	 * @param int | string $info 
	 * @return bool
	 */

	public final  function exists(int | string $info) {

	}


	/**
	 * @access public
	 * @param int | string $info 
	 * @return Personnage
	 */

	public final  function get(int | string $info) {

	}


	/**
	 * @access public
	 * @param string $nom 
	 * @return array
	 */

	public final  function getList($nom) {

	}


	/**
	 * @access public
	 * @param Personnage $pserso 
	 * @return void
	 */

	public final  function update(Personnage $pserso) {

	}


}
?>